// Status generated by gorm.io/gen. DO NOT EDIT.
// Status generated by gorm.io/gen. DO NOT EDIT.
// Status generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameConfig = "config"

// Config mapped from table <config>
type Config struct {
	ID        int64     `gorm:"column:id;type:INTEGER" json:"id"`
	Config    string    `gorm:"column:config;type:TEXT" json:"config"`
	Value     string    `gorm:"column:value;type:TEXT" json:"value"`
	Num       int64     `gorm:"column:num;type:INTEGER" json:"num"`
	Extra     string    `gorm:"column:extra;type:TEXT" json:"extra"`
	CreatedAt time.Time `gorm:"column:created_at;type:datetime" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;type:datetime" json:"updated_at"`
}

// TableName Config's table name
func (*Config) TableName() string {
	return TableNameConfig
}
