// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID          int64     `gorm:"column:id;type:INTEGER" json:"id"`
	Name        string    `gorm:"column:name;type:TEXT" json:"name"`
	Password    string    `gorm:"column:password;type:TEXT" json:"password"`
	Header      string    `gorm:"column:header;type:TEXT" json:"header"`
	Gender      string    `gorm:"column:gender;type:TEXT" json:"gender"`
	Role        string    `gorm:"column:role;type:TEXT" json:"role"`
	Status      int64     `gorm:"column:status;type:INTEGER" json:"status"`
	AuthVersion int64     `gorm:"column:auth_version;type:INTEGER" json:"auth_version"`
	Sign        string    `gorm:"column:sign;type:TEXT" json:"sign"`
	CreatedAt   time.Time `gorm:"column:created_at;type:datetime" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;type:datetime" json:"updated_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
