package common

const (
	CodeOk      = 0
	CodeFailure = 1

	SrvPath = "/srv"
	WebPath = "/web"

	UserDefaultHeader = "/9j/2wCEAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRQBAwQE" +
		"BQQFCQUFCRQNCw0UFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFP/AABEIAGQAZAMBIgAC" +
		"EQEDEQH/xAGiAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBwgJCgsQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQy" +
		"gZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeI" +
		"iYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+gEAAwEBAQEB" +
		"AQEBAQAAAAAAAAECAwQFBgcICQoLEQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIygQgUQpGhscEJIzNS8BVictEK" +
		"FiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqCg4SFhoeIiYqSk5SVlpeYmZqio6Sl" +
		"pqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2dri4+Tl5ufo6ery8/T19vf4+fr/2gAMAwEAAhEDEQA/AP0tooooAKKKKACi" +
		"iigAooooAKKKKACiiigAooooAKKKKACiiigAopk0yW8LyyMFjQFmY9hXm2ueLrvVJmWGRre1BwqIcEj1JoA9NxSV49b6ld2kgkiu" +
		"ZUcc5DmvQPCfif8AtuNoJwFu4xkkcBx60AdDRRRQAUUUUAFFFFABRRRQAUUUUAc947uGh0BlU48yRUP05P8ASvNq9U8U6c2p6JPF" +
		"GN0q4dR6kf8A1s15X0oAK1PDE7W+v2TJ/FIEP0PFZdb3grTnvdbil2/urf52b37CgD0yiiigAooooAKKKKACiiigAoopGYIpZiFU" +
		"ckk4AoAWvNvHGnw2GsBoQFEyeYyDsc4P510GteO7az3RWQF1KON/8A/xrhL29m1C5ee4cySt1J/lQBDXq3hrT4dP0e3WIDMiCR3/" +
		"ALxIrymug0DxhcaOiwSr9otR0UnDL9D/AEoA9KoqjpetWesR7raUMw6xnhl+oq9QAUUUUAFFFFABRRRQAteW+IfEl1rFxIhcx2ysQ" +
		"sSng47n1r1KuPn+HUMkzul7IisxIUxg4/HNAHCUV3H/AAreP/oIP/36H+NH/Ct4/wDoIP8A9+h/jQBw9Fdx/wAK3j/6CD/9+h/jR/" +
		"wreP8A6CD/APfof40AcVDPJbSrJE7RyLyGU4Ir0jwfrs2tWUouADNCQpcfxZ7/AF4rM/4VvH/0EH/79D/Gt3w94ej8PwyokrTNKw" +
		"LMwx06cUAatFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFAH//"
)
